name: _Tests cpython coverage

on:
    push:
        branches: [te-*]
    workflow_dispatch:

jobs:
    cov:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -e .[testing] --verbose
        - name: Check gcc
          continue-on-error: true
          run: |
            gcc --version
          shell: bash
        - name: Check gcov
          continue-on-error: true
          run: |
            gcov --version
          shell: bash
        - name: Build extension
          run: |
            python3 setup.py build_ext --verbose
        - name: Checks
          run: |
            echo "${{github.workspace}}"
            find ${{github.workspace}}
          shell: bash