name: Tests

on:
   workflow_call:
     inputs:
       ref:
         required: false
         type: string
         default: ${{github.ref_name}}
       os:
         required: true
         type: string
       py:
         required: true
         type: string
       lint:
         required: false
         type: string
         default: ''
       typecheck:
         required: false
         type: string
         default: ''
     secrets:
       token:
         required: true

jobs:
  test:
    continue-on-error: true
    runs-on: ${{inputs.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sammnnz/geompy
          ref: ${{inputs.ref}}
      - name: Setup Python ${{inputs.py}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{inputs.py}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,linting,typechecking]
      - name: Download coverage artefact
        continue-on-error: true
        uses: actions/download-artifact@v4.1.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true
          name: geompy-cov
          path: .coverage
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --cov-append --verbose --color=yes --assert=plain
          coverage xml
      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: geompy-cov
          overwrite: true
          path: |
            .coverage/coverage.-1
            coverage.xml
      - name: Linter
        if: ${{inputs.lint}}
        run: |
          flake8 src tests
      - name: Type-checker
        if: ${{inputs.typecheck}}
        run: |
          mypy src