name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -e .
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --verbose --color=yes --cov=pymagic --cov-append --assert=plain
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          verbose: true