name: Tests-ub-win

on:
   pull_request:
     branches: [main, release-*, develop, fe-*]
     types: [opened, reopened]
   workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: [3.7, 3.8, 3.9, "3.10"]
        exclude:
          - os: ubuntu-latest
            py: "3.7"
        include:
          - os: ubuntu-22.04
            py: "3.7.17"
          - os: windows-latest
            py: "3.9"
            lint: "true"
            typecheck: "true"
    uses: ./.github/workflows/tests.yml
    with:
        os: ${{matrix.os}}
        py: ${{matrix.py}}
        lint: ${{matrix.lint}}
        typecheck: ${{matrix.typecheck}}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}