name: Tests

on:
   workflow_call:
     inputs:
       ref:
         required: false
         type: string
         default: ${{github.ref_name}}
       os:
         required: true
         type: string
       py:
         required: true
         type: string
       lint:
         required: false
         type: string
         default: ''
       typecheck:
         required: false
         type: string
         default: ''
     secrets:
       token:
         required: true

jobs:
  test:
    runs-on: ${{inputs.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sammnnz/geompy
          ref: ${{inputs.ref}}
      - name: Setup Python ${{inputs.py}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{inputs.py}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[testing,linting,typechecking]
      - name: Test with pytest
        run: |
          pytest --cov-config=.coveragerc --verbose --color=yes --assert=plain
      - name: Change '.coverage' file name
        run: |
          mv .coverage/coverage.-1 .coverage/coverage-${{inputs.os}}-py${{inputs.py}}.-1
        shell: bash
      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: geompy-cov-${{inputs.os}}-py${{inputs.py}}
          overwrite: true
          path: .coverage/coverage-${{inputs.os}}-py${{inputs.py}}.-1
      - name: Linter
        if: ${{inputs.lint}}
        run: |
          flake8 src tests
      - name: Type-checker
        if: ${{inputs.typecheck}}
        run: |
          mypy src
