name: Tests (single OS and single PY)

on:
   workflow_dispatch:
     inputs:
       os:
         required: true
         type: choice
         default: 'windows-latest'
         options:
         # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#standard-github-hosted-runners-for-public-repositories
         - ubuntu-latest
         - ubuntu-24.04
         - ubuntu-22.04
         - ubuntu-20.04
         - windows-latest
         - windows-2025
         - windows-2022
         - windows-2019
         - ubuntu-24.04-arm
         - ubuntu-22.04-arm
         - macos-13
         - macos-latest
         - macos-14
         - macos-15
       py:
         required: true
         type: choice
         default: '3.9'
         options:
         - '3.7'
         - '3.8'
         - '3.9'
         - '3.10'
       cov:
         required: false
         type: choice
         default: 'false'
         options:
           - 'true'
           - 'false'
       lint:
         required: false
         type: choice
         default: 'false'
         options:
         - 'true'
         - 'false'
       typecheck:
         required: false
         type: choice
         default: 'false'
         options:
         - 'true'
         - 'false'

jobs:
  tests-call:
     uses: ./.github/workflows/tests_imp.yml
     with:
       os: ${{inputs.os}}
       py: ${{inputs.py}}
       cov: ${{inputs.cov}}
       lint: ${{inputs.lint}}
       typecheck: ${{inputs.typecheck}}
     secrets:
       token: ${{secrets.GITHUB_TOKEN}}